flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Diff-0.3.4
- HTF-0.13.1.0
- HUnit-1.5.0.0
- Hclip-3.0.0.4
- MonadRandom-0.5
- QuickCheck-2.9.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.1.0.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- cabal-helper-0.7.3.0
- call-stack-0.1.0
- clock-0.7.2
- cmdargs-0.10.14
- comonad-5
- contravariant-1.4
- cpphs-1.20.2
- distributive-0.5.1
- djinn-ghc-0.0.2.3
- djinn-lib-0.0.1.2
- dlist-0.8.0.2
- either-4.4.1.1
- exceptions-0.8.3
- extra-1.5.1
- fail-4.9.0.0
- fclabels-2.0.3.2
- free-4.12.4
- ghc-mod-5.7.0.0
- ghc-paths-0.1.0.9
- ghc-syb-utils-0.2.3
- hashable-1.2.5.0
- haskell-src-1.0.2.0
- haskell-src-exts-1.18.2
- hlint-1.9.39
- hscolour-1.24.1
- integer-logarithms-1
- kan-extensions-5.0.1
- lens-4.15.1
- lifted-base-0.2.3.8
- mmorph-1.0.9
- monad-control-1.0.1.0
- monad-journal-0.7.2
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.13.0.0
- parallel-3.2.1.0
- parsec-3.1.11
- pipes-4.3.2
- polyparse-1.12
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2
- random-1.1
- refact-0.3.0.2
- reflection-2.1.2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- safe-0.3.10
- scientific-0.3.4.10
- semigroupoids-5.1
- semigroups-0.18.2
- split-0.2.3.1
- stm-2.4.4.1
- strict-0.3.2
- syb-0.6
- tagged-0.8.5
- temporary-1.2.0.4
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- uniplate-1.6.12
- unordered-containers-0.2.7.2
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vector-0.12.0.0
- void-0.7.1
- xmlgen-0.6.2.1
resolver: ghc-8.0.2
